server:
  port: 8083

spring:
  application:
    name: e-health-insurance-claim
  datasource:
    url: jdbc:postgresql://localhost:5432/ehi_claim
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: claim-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ehi.infra.event
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:85071bbb13fe61a58f2e02f1980865290972d955f35d469f0a52160f922527c7925057cff3cd4af96b9d6fbc84d9b84d82d766d1e59e998482763209574bb4d6}

app:
  upload-dir: ${UPLOAD_DIR:./uploads/claims}
