plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.ehi'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInteger())
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api libs.jackson.databind
    api libs.jackson.annotations
    api libs.jakarta.validation

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
