server:
  port: 8080

spring:
  application:
    name: e-health-insurance-gw
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
        - id: plans
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/plans/**
        - id: policies
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/policies/**
        - id: claims
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/claims/**
        - id: payments
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/payments/**
        - id: ai
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/ai/**
        - id: notifications
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/notifications/**

jwt:
  secret: ${JWT_SECRET:85071bbb13fe61a58f2e02f1980865290972d955f35d469f0a52160f922527c7925057cff3cd4af96b9d6fbc84d9b84d82d766d1e59e998482763209574bb4d6}

gateway:
  security:
    public-paths:
      - /api/v1/auth/**
    public-get-paths:
      - /api/v1/plans/**
